name: ecosort_dbt
version: "1.0.0"
config-version: 2

profile: ecosort

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecosort_dbt:
    gold:
      +materialized: table
